version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn main:apps --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/apps
    env_file:
      - ./backend/.env.dev
  mongodb-service:
    image: mongo:5.0.3
    logging:
      driver: none
    ports:
      - "27017:27017"
    volumes:
      - mongodb_volume:/data/db

volumes:
  mongodb_volume: